export let Adventures = [
    "https://www.archive.org/download/adventuressherlockholmes_v4_1501_librivox/adventuresofsherlockholmes_@_doyle_64kb.mp3",
    "*A Scandal in Bohemia",
    "*The Red Headed League",
    "-A Case of Identity",
    "*The Boscombe Valley Mystery",
    "-The Five Orange Pips",
    "*The Man With the Twisted Lip",
    "*The Blue Carbuncle",
    "-The Speckled Band",
    "-The Engineer's Thumb",
    "*The Noble Bachelor",
    "*The Beryl Coronet",
    "*The Copper Beeches",
]
    
export let Memoirs = [
"https://www.archive.org/download/memoirsofsherlockholmesv3_1502_librivox/memoirsofsherlockholmes_@_doyle_64kb.mp3",
"*Silver Blaze",
"*The Yellow Face",
"*The Stock Broker's Clerk",
"*The Gloria Scott",
"*The Musgrave Ritual",
"*The Reigate Puzzle",
"*The Crooked Man",
"*The Resident Patient",
"*The Greek Interpreter",
"*The Naval Treaty Part 1",
"^The Naval Treaty Part 2",
"-The Final Problem",
]

export let Return = [
    "https://www.archive.org/download/returnsherlockholmes_v3_1507_librivox/returnofsherlockholmes_01_doyle_64kb.mp3",
    "*The Empty House",
    "*The Norwood Builder",
    "*The Dancing Men",
    "*The Solitary Bicyclist",
    "*The Priory School Part 1",
    "^The Priory School Part 2",
    "*Black Peter",
    "-Charles Augustus Milverton",
    "*The Six Napoleons",
    "*The Three Students",
    "*The Golden Pince-Nez",
    "*The Missing Three-Quarter",
    "*The Abbey Grange",
    "*The Second Stain",
]
