export let Adventures = [
    "https://www.archive.org/download/adventuressherlockholmes_v4_1501_librivox/adventuresofsherlockholmes_@_doyle_64kb.mp3",
    "*A Scandal in Bohemia",
    "*The Red Headed League",
    "-A Case of Identity",
    "*The Boscombe Valley Mystery",
    "-The Five Orange Pips",
    "*The Man With the Twisted Lip",
    "*The Blue Carbuncle",
    "-The Speckled Band",
    "-The Engineer's Thumb",
    "*The Noble Bachelor",
    "*The Beryl Coronet",
    "*The Copper Beeches",
]
    
export let Memoirs = [
"https://www.archive.org/download/memoirsofsherlockholmesv3_1502_librivox/memoirsofsherlockholmes_@_doyle_64kb.mp3",
"*Silver Blaze",
"*The Yellow Face",
"*The Stock Broker's Clerk",
"*The Gloria Scott",
"*The Musgrave Ritual",
"*The Reigate Puzzle",
"*The Crooked Man",
"*The Resident Patient",
"*The Greek Interpreter",
"*The Naval Treaty Part 1",
"^The Naval Treaty Part 2",
"-The Final Problem",
]

export let Return = [
    "https://www.archive.org/download/returnsherlockholmes_v3_1507_librivox/returnofsherlockholmes_@_doyle_64kb.mp3",
    "*The Empty House",
    "*The Norwood Builder",
    "*The Dancing Men",
    "*The Solitary Bicyclist",
    "*The Priory School Part 1",
    "^The Priory School Part 2",
    "*Black Peter",
    "-Charles Augustus Milverton",
    "*The Six Napoleons",
    "*The Three Students",
    "*The Golden Pince-Nez",
    "*The Missing Three-Quarter",
    "*The Abbey Grange",
    "*The Second Stain",
];
export let LastBow = [
    "https://ia800205.us.archive.org/34/items/his_last_bow_version_3_1603_librivox/hislastbow_@_doyle_128kb.mp3",
    "*Wisteria Lodge",
    "^Wisteria Lodge Part II",
    "*Cardboard Box",
    "*Red Circle",
    "^Red Circle Part II",
    "*Bruce-Partington Plans",
    "-Dying Detective",
    "*Lady Frances Carfax",
    "*The Devil's Foot",
    "*His Last Bow"
];
export let Casebook = [
    "https://ia601606.us.archive.org/22/items/casebooksherlockholmes_2303_librivox/casebookofsherlockholmes_@_doyle_64kb.mp3",
    "*The Illustrious Client",
    "*The Blanched Soldier",
    "*The Mazarin Stone",
    "*The Three Gables",
    "*The Sussex Vampire",
    "*The Three Garridebs",
    "*Thor Bridge",
    "*The Creeping Man",
    "*The Lion's Mane",
    "*The Veiled Lodger",
    "*Shoscombe Old Place",
    "*The Retired Colourman"
    ]
